-- Queue SEO refresh requests (annonce pages + sitemap) after moderation approvals.
-- This supports a local scheduled worker that runs deploy:server:seo-refresh only
-- when a refresh was requested from the admin UI.

CREATE TABLE IF NOT EXISTS public.seo_refresh_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_type text NOT NULL DEFAULT 'seo_refresh_annonces',
  target text NOT NULL DEFAULT 'annonces',
  source text NOT NULL DEFAULT 'admin_moderation',
  status text NOT NULL DEFAULT 'pending',
  requested_by uuid,
  annonce_id bigint,
  reason text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  dedupe_key text,
  started_at timestamptz,
  processed_at timestamptz,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seo_refresh_requests_status_check
    CHECK (status IN ('pending', 'processing', 'done', 'failed', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_seo_refresh_requests_status_created
  ON public.seo_refresh_requests(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_seo_refresh_requests_request_type
  ON public.seo_refresh_requests(request_type);

CREATE INDEX IF NOT EXISTS idx_seo_refresh_requests_annonce_id
  ON public.seo_refresh_requests(annonce_id);

ALTER TABLE public.seo_refresh_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "seo_refresh_requests_admin_select" ON public.seo_refresh_requests;
CREATE POLICY "seo_refresh_requests_admin_select"
  ON public.seo_refresh_requests
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND is_admin = true
    )
  );

DROP POLICY IF EXISTS "seo_refresh_requests_admin_insert" ON public.seo_refresh_requests;
CREATE POLICY "seo_refresh_requests_admin_insert"
  ON public.seo_refresh_requests
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND is_admin = true
    )
  );
