-- =====================================================
-- Feedback system: public submit + admin visibility
-- Date: 2026-02-19
-- =====================================================

-- Rename legacy table if needed.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'feedbacks'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'feedback'
  ) THEN
    ALTER TABLE public.feedbacks RENAME TO feedback;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  email TEXT,
  page_url TEXT NOT NULL,
  page_path TEXT,
  page_title TEXT,
  referrer TEXT,
  user_agent TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.feedback
  ADD COLUMN IF NOT EXISTS message TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS page_url TEXT,
  ADD COLUMN IF NOT EXISTS page_path TEXT,
  ADD COLUMN IF NOT EXISTS page_title TEXT,
  ADD COLUMN IF NOT EXISTS referrer TEXT,
  ADD COLUMN IF NOT EXISTS user_agent TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

UPDATE public.feedback
SET message = '[message manquant]'
WHERE message IS NULL OR BTRIM(message) = '';

UPDATE public.feedback
SET page_url = COALESCE(NULLIF(BTRIM(page_url), ''), NULLIF(BTRIM(page_path), ''), 'unknown')
WHERE page_url IS NULL OR BTRIM(page_url) = '';

UPDATE public.feedback
SET status = CASE
  WHEN LOWER(COALESCE(status, '')) IN ('new', 'nouveau', 'pending') THEN 'new'
  WHEN LOWER(COALESCE(status, '')) IN ('in_progress', 'in progress', 'processing', 'encours', 'en cours') THEN 'in_progress'
  WHEN LOWER(COALESCE(status, '')) IN ('processed', 'traite', 'traité', 'published', 'archived', 'done') THEN 'processed'
  ELSE 'new'
END;

UPDATE public.feedback
SET created_at = COALESCE(created_at, NOW())
WHERE created_at IS NULL;

UPDATE public.feedback
SET updated_at = COALESCE(updated_at, created_at, NOW())
WHERE updated_at IS NULL;

ALTER TABLE public.feedback
  ALTER COLUMN message SET NOT NULL,
  ALTER COLUMN page_url SET NOT NULL,
  ALTER COLUMN status SET DEFAULT 'new',
  ALTER COLUMN status SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT NOW(),
  ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN updated_at SET DEFAULT NOW(),
  ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'feedback_status_check'
      AND conrelid = 'public.feedback'::regclass
  ) THEN
    ALTER TABLE public.feedback
      ADD CONSTRAINT feedback_status_check
      CHECK (status IN ('new', 'in_progress', 'processed'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON public.feedback(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_status ON public.feedback(status);
CREATE INDEX IF NOT EXISTS idx_feedback_page_url ON public.feedback(page_url);

CREATE OR REPLACE FUNCTION public.set_feedback_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_feedback_updated_at ON public.feedback;
CREATE TRIGGER trg_set_feedback_updated_at
BEFORE UPDATE ON public.feedback
FOR EACH ROW
EXECUTE FUNCTION public.set_feedback_updated_at();

ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "feedback_insert_all" ON public.feedback;
CREATE POLICY "feedback_insert_all"
  ON public.feedback
  FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "feedback_select_all" ON public.feedback;
CREATE POLICY "feedback_select_all"
  ON public.feedback
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "feedback_update_all" ON public.feedback;
CREATE POLICY "feedback_update_all"
  ON public.feedback
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "feedback_delete_all" ON public.feedback;
CREATE POLICY "feedback_delete_all"
  ON public.feedback
  FOR DELETE
  USING (true);
