-- =====================================================
-- Restore missing admin tables expected by frontend
-- Date: 2026-02-19
-- =====================================================

-- -----------------------------------------------------
-- JOB RUNS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.job_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  status text NOT NULL DEFAULT 'unknown',
  dedupe_key text,
  result jsonb,
  error_message text,
  executed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_job_runs_action ON public.job_runs(action);
CREATE INDEX IF NOT EXISTS idx_job_runs_status ON public.job_runs(status);
CREATE INDEX IF NOT EXISTS idx_job_runs_created_at ON public.job_runs(created_at DESC);

ALTER TABLE public.job_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "job_runs_select_all" ON public.job_runs;
CREATE POLICY "job_runs_select_all"
  ON public.job_runs
  FOR SELECT
  USING (true);

-- -----------------------------------------------------
-- REPORTS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text,
  report_type text,
  category text,
  status text NOT NULL DEFAULT 'Nouveau',
  state text,
  reporter_pseudo text,
  reporter_name text,
  reporter_email text,
  reporter_id uuid,
  reported_content text,
  content_title text,
  annonce_title text,
  listing_title text,
  reported_user text,
  reported_user_id uuid,
  target_user text,
  target_user_pseudo text,
  description text,
  reason text,
  details text,
  message text,
  evidence text[] NOT NULL DEFAULT ARRAY[]::text[],
  evidence_urls text[] NOT NULL DEFAULT ARRAY[]::text[],
  attachments text[] NOT NULL DEFAULT ARRAY[]::text[],
  submitted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reports_created_at ON public.reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reports_status ON public.reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_type ON public.reports(type);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reports_select_all" ON public.reports;
CREATE POLICY "reports_select_all"
  ON public.reports
  FOR SELECT
  USING (true);

-- -----------------------------------------------------
-- SUBCATEGORIES (with FK relation for PostgREST embedding)
-- -----------------------------------------------------
DO $$
DECLARE
  categories_id_type text;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod)
  INTO categories_id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'categories'
    AND a.attname = 'id'
    AND a.attnum > 0
    AND NOT a.attisdropped;

  IF categories_id_type IS NULL THEN
    RAISE EXCEPTION 'public.categories.id introuvable';
  END IF;

  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS public.subcategories (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      category_id %s NOT NULL,
      name text NOT NULL,
      nom text,
      slug text,
      icon_url text,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now()
    )',
    categories_id_type
  );
END $$;

DO $$
BEGIN
  ALTER TABLE public.subcategories
    ADD CONSTRAINT subcategories_category_id_fkey
    FOREIGN KEY (category_id)
    REFERENCES public.categories(id)
    ON DELETE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_subcategories_category_id ON public.subcategories(category_id);
CREATE INDEX IF NOT EXISTS idx_subcategories_name ON public.subcategories(name);
CREATE UNIQUE INDEX IF NOT EXISTS uq_subcategories_category_name ON public.subcategories(category_id, name);

ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "subcategories_select_all" ON public.subcategories;
CREATE POLICY "subcategories_select_all"
  ON public.subcategories
  FOR SELECT
  USING (true);

-- Optional compatibility alias used by some environments
DO $$
DECLARE
  rel_kind "char";
BEGIN
  SELECT c.relkind
  INTO rel_kind
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'signalements';

  IF rel_kind IS NULL THEN
    EXECUTE 'CREATE VIEW public.signalements AS SELECT * FROM public.reports';
  ELSIF rel_kind = 'v' THEN
    EXECUTE 'CREATE OR REPLACE VIEW public.signalements AS SELECT * FROM public.reports';
  ELSE
    RAISE NOTICE 'public.signalements existe deja et n''est pas une vue; alias ignore';
  END IF;
END $$;

-- Quick verification
SELECT COUNT(*) AS job_runs_count FROM public.job_runs;
SELECT COUNT(*) AS reports_count FROM public.reports;
SELECT COUNT(*) AS subcategories_count FROM public.subcategories;
