-- Strategy B for long rentals:
-- - keep a reusable card on file
-- - rotate deposit authorizations before each capture_before deadline
-- - keep an auditable history of each authorization cycle

CREATE TABLE IF NOT EXISTS public.reservation_deposit_strategy_b (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id uuid NOT NULL REFERENCES public.reservations(id) ON DELETE CASCADE,
  renter_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  strategy text NOT NULL DEFAULT 'strategy_b',
  status text NOT NULL DEFAULT 'scheduled',
  currency text NOT NULL DEFAULT 'eur',
  deposit_amount_cents integer NOT NULL CHECK (deposit_amount_cents > 0),
  stripe_customer_id text NOT NULL,
  stripe_payment_method_id text NOT NULL,
  current_payment_intent_id text,
  current_capture_before timestamptz,
  hold_required_from timestamptz NOT NULL,
  hold_required_until timestamptz NOT NULL,
  next_reauthorization_due_at timestamptz NOT NULL,
  last_rotation_at timestamptz,
  cycle_index integer NOT NULL DEFAULT 0 CHECK (cycle_index >= 0),
  reauth_required_at timestamptz,
  released_at timestamptz,
  captured_at timestamptz,
  last_error_code text,
  last_error_message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reservation_deposit_strategy_b_unique_reservation UNIQUE (reservation_id),
  CONSTRAINT reservation_deposit_strategy_b_strategy_check CHECK (strategy IN ('strategy_b')),
  CONSTRAINT reservation_deposit_strategy_b_status_check CHECK (
    status IN (
      'scheduled',
      'active',
      'reauth_required',
      'released',
      'captured',
      'expired',
      'cancelled',
      'failed',
      'not_required'
    )
  ),
  CONSTRAINT reservation_deposit_strategy_b_window_check CHECK (hold_required_until >= hold_required_from)
);

CREATE INDEX IF NOT EXISTS idx_reservation_deposit_strategy_b_due
  ON public.reservation_deposit_strategy_b(status, next_reauthorization_due_at);

CREATE INDEX IF NOT EXISTS idx_reservation_deposit_strategy_b_reservation
  ON public.reservation_deposit_strategy_b(reservation_id);

CREATE TABLE IF NOT EXISTS public.reservation_deposit_strategy_b_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strategy_id bigint REFERENCES public.reservation_deposit_strategy_b(id) ON DELETE CASCADE,
  reservation_id uuid NOT NULL REFERENCES public.reservations(id) ON DELETE CASCADE,
  cycle_index integer NOT NULL DEFAULT 0,
  event_type text NOT NULL,
  stripe_payment_intent_id text,
  capture_before timestamptz,
  error_code text,
  error_message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reservation_deposit_strategy_b_events_event_type_check CHECK (
    event_type IN (
      'scheduled',
      'authorization_created',
      'authorization_rotated',
      'authorization_cancelled',
      'authorization_released',
      'authorization_captured',
      'authorization_expired',
      'requires_action',
      'failed'
    )
  )
);

CREATE INDEX IF NOT EXISTS idx_reservation_deposit_strategy_b_events_reservation
  ON public.reservation_deposit_strategy_b_events(reservation_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_reservation_deposit_strategy_b_events_strategy
  ON public.reservation_deposit_strategy_b_events(strategy_id, created_at DESC);

ALTER TABLE public.reservation_deposit_strategy_b ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservation_deposit_strategy_b_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reservation_deposit_strategy_b_participants_select" ON public.reservation_deposit_strategy_b;
CREATE POLICY "reservation_deposit_strategy_b_participants_select"
  ON public.reservation_deposit_strategy_b
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.reservations r
      WHERE r.id = reservation_id
        AND auth.uid() IN (r.owner_id, r.renter_id)
    )
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.is_admin = true
    )
  );

DROP POLICY IF EXISTS "reservation_deposit_strategy_b_events_participants_select" ON public.reservation_deposit_strategy_b_events;
CREATE POLICY "reservation_deposit_strategy_b_events_participants_select"
  ON public.reservation_deposit_strategy_b_events
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.reservations r
      WHERE r.id = reservation_id
        AND auth.uid() IN (r.owner_id, r.renter_id)
    )
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.is_admin = true
    )
  );

CREATE OR REPLACE FUNCTION public.touch_reservation_deposit_strategy_b_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_reservation_deposit_strategy_b ON public.reservation_deposit_strategy_b;
CREATE TRIGGER trg_touch_reservation_deposit_strategy_b
BEFORE UPDATE ON public.reservation_deposit_strategy_b
FOR EACH ROW
EXECUTE FUNCTION public.touch_reservation_deposit_strategy_b_updated_at();
