-- Official inspection model (completion):
-- - 24h dispute window after end-of-rental inspection closure
-- - strict dispute opening (selected photos + detailed description + deadline)
-- - internal arbitration scope (platform-only evidence rules)
-- - automatic settlement state transition: hold -> release / moderation freeze

CREATE TABLE IF NOT EXISTS public.reservation_inspection_settlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id uuid NOT NULL REFERENCES public.reservations(id) ON DELETE CASCADE,
  end_session_id bigint REFERENCES public.reservation_inspection_sessions(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending_end_inspection',
  payment_hold_status text NOT NULL DEFAULT 'none',
  hold_started_at timestamptz,
  contest_window_ends_at timestamptz,
  auto_release_eligible_at timestamptz,
  dispute_opened_at timestamptz,
  payment_frozen_at timestamptz,
  payment_released_at timestamptz,
  final_decision_at timestamptz,
  dispute_count integer NOT NULL DEFAULT 0,
  latest_dispute_id bigint,
  legal_scope_note text NOT NULL DEFAULT 'Pour l?arbitrage interne de la plateforme, seules les photos d?etat des lieux prises via le module officiel et les traces techniques associees sont prises en compte.',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reservation_inspection_settlements_unique_reservation UNIQUE (reservation_id),
  CONSTRAINT reservation_inspection_settlements_status_check CHECK (
    status IN (
      'pending_end_inspection',
      'hold_24h',
      'disputed_pending_moderation',
      'released_no_dispute',
      'released_after_moderation',
      'captured_after_moderation'
    )
  ),
  CONSTRAINT reservation_inspection_settlements_payment_hold_status_check CHECK (
    payment_hold_status IN ('none', 'hold_24h', 'frozen_for_moderation', 'released', 'captured')
  )
);

CREATE INDEX IF NOT EXISTS idx_reservation_inspection_settlements_status_due
  ON public.reservation_inspection_settlements(status, auto_release_eligible_at);

CREATE INDEX IF NOT EXISTS idx_reservation_inspection_settlements_reservation
  ON public.reservation_inspection_settlements(reservation_id);

CREATE TABLE IF NOT EXISTS public.reservation_inspection_disputes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id uuid NOT NULL REFERENCES public.reservations(id) ON DELETE CASCADE,
  settlement_id bigint REFERENCES public.reservation_inspection_settlements(id) ON DELETE SET NULL,
  opened_by_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  opened_by_role text NOT NULL,
  status text NOT NULL DEFAULT 'opened',
  title text,
  description text NOT NULL,
  opened_at timestamptz NOT NULL DEFAULT now(),
  window_ends_at timestamptz,
  submitted_within_window boolean NOT NULL DEFAULT true,
  moderator_user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  moderator_decision text,
  moderator_note text,
  resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reservation_inspection_disputes_opened_by_role_check CHECK (opened_by_role IN ('owner', 'renter')),
  CONSTRAINT reservation_inspection_disputes_status_check CHECK (
    status IN (
      'opened',
      'under_review',
      'pending_information',
      'resolved_release',
      'resolved_capture',
      'rejected',
      'withdrawn'
    )
  ),
  CONSTRAINT reservation_inspection_disputes_moderator_decision_check CHECK (
    moderator_decision IS NULL OR moderator_decision IN ('release', 'capture', 'reject')
  )
);

CREATE INDEX IF NOT EXISTS idx_reservation_inspection_disputes_reservation
  ON public.reservation_inspection_disputes(reservation_id, opened_at DESC);

CREATE INDEX IF NOT EXISTS idx_reservation_inspection_disputes_status
  ON public.reservation_inspection_disputes(status, opened_at DESC);

CREATE TABLE IF NOT EXISTS public.reservation_inspection_dispute_photos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispute_id bigint NOT NULL REFERENCES public.reservation_inspection_disputes(id) ON DELETE CASCADE,
  reservation_id uuid NOT NULL REFERENCES public.reservations(id) ON DELETE CASCADE,
  photo_id_text text NOT NULL,
  photo_phase text,
  photo_url_snapshot text,
  selected_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT reservation_inspection_dispute_photos_unique UNIQUE (dispute_id, photo_id_text)
);

CREATE INDEX IF NOT EXISTS idx_reservation_inspection_dispute_photos_dispute
  ON public.reservation_inspection_dispute_photos(dispute_id);

ALTER TABLE public.reservation_inspection_settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservation_inspection_disputes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservation_inspection_dispute_photos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "inspection_settlements_participants_select" ON public.reservation_inspection_settlements;
CREATE POLICY "inspection_settlements_participants_select"
  ON public.reservation_inspection_settlements
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.reservations r
      WHERE r.id = reservation_id
        AND auth.uid() IN (r.owner_id, r.renter_id)
    )
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.is_admin = true
    )
  );

DROP POLICY IF EXISTS "inspection_disputes_participants_select" ON public.reservation_inspection_disputes;
CREATE POLICY "inspection_disputes_participants_select"
  ON public.reservation_inspection_disputes
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.reservations r
      WHERE r.id = reservation_id
        AND auth.uid() IN (r.owner_id, r.renter_id)
    )
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.is_admin = true
    )
  );

DROP POLICY IF EXISTS "inspection_dispute_photos_participants_select" ON public.reservation_inspection_dispute_photos;
CREATE POLICY "inspection_dispute_photos_participants_select"
  ON public.reservation_inspection_dispute_photos
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.reservations r
      WHERE r.id = reservation_id
        AND auth.uid() IN (r.owner_id, r.renter_id)
    )
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.is_admin = true
    )
  );

CREATE OR REPLACE FUNCTION public.touch_reservation_inspection_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_reservation_inspection_settlements ON public.reservation_inspection_settlements;
CREATE TRIGGER trg_touch_reservation_inspection_settlements
BEFORE UPDATE ON public.reservation_inspection_settlements
FOR EACH ROW
EXECUTE FUNCTION public.touch_reservation_inspection_updated_at();

DROP TRIGGER IF EXISTS trg_touch_reservation_inspection_disputes ON public.reservation_inspection_disputes;
CREATE TRIGGER trg_touch_reservation_inspection_disputes
BEFORE UPDATE ON public.reservation_inspection_disputes
FOR EACH ROW
EXECUTE FUNCTION public.touch_reservation_inspection_updated_at();

CREATE OR REPLACE FUNCTION public.ensure_inspection_settlement_on_end_close()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
BEGIN
  IF lower(coalesce(NEW.phase, '')) <> 'end' THEN
    RETURN NEW;
  END IF;

  IF NEW.closed_at IS NULL THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' AND OLD.closed_at IS NOT NULL AND OLD.closed_at IS NOT DISTINCT FROM NEW.closed_at THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.reservation_inspection_settlements (
    reservation_id,
    end_session_id,
    status,
    payment_hold_status,
    hold_started_at,
    contest_window_ends_at,
    auto_release_eligible_at,
    metadata,
    created_at,
    updated_at
  )
  VALUES (
    NEW.reservation_id,
    NEW.id,
    'hold_24h',
    'hold_24h',
    NEW.closed_at,
    coalesce(NEW.contest_window_ends_at, NEW.closed_at + interval '24 hours'),
    coalesce(NEW.contest_window_ends_at, NEW.closed_at + interval '24 hours'),
    jsonb_build_object(
      'source', 'inspection_end_session_close',
      'phase', NEW.phase,
      'internal_arbitration_scope_only', true
    ),
    now(),
    now()
  )
  ON CONFLICT (reservation_id)
  DO UPDATE SET
    end_session_id = excluded.end_session_id,
    status = CASE
      WHEN public.reservation_inspection_settlements.status IN ('released_no_dispute', 'released_after_moderation', 'captured_after_moderation')
      THEN public.reservation_inspection_settlements.status
      ELSE 'hold_24h'
    END,
    payment_hold_status = CASE
      WHEN public.reservation_inspection_settlements.payment_hold_status IN ('released', 'captured')
      THEN public.reservation_inspection_settlements.payment_hold_status
      ELSE 'hold_24h'
    END,
    hold_started_at = coalesce(public.reservation_inspection_settlements.hold_started_at, excluded.hold_started_at),
    contest_window_ends_at = excluded.contest_window_ends_at,
    auto_release_eligible_at = excluded.auto_release_eligible_at,
    metadata = coalesce(public.reservation_inspection_settlements.metadata, '{}'::jsonb) || excluded.metadata,
    updated_at = now();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ensure_inspection_settlement_on_end_close ON public.reservation_inspection_sessions;
CREATE TRIGGER trg_ensure_inspection_settlement_on_end_close
AFTER INSERT OR UPDATE ON public.reservation_inspection_sessions
FOR EACH ROW
EXECUTE FUNCTION public.ensure_inspection_settlement_on_end_close();

CREATE OR REPLACE FUNCTION public.open_reservation_inspection_dispute(
  p_reservation_id uuid,
  p_selected_photo_ids text[],
  p_description text,
  p_title text DEFAULT NULL
)
RETURNS public.reservation_inspection_disputes
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_role text := coalesce(auth.role(), '');
  v_reservation record;
  v_participant_role text;
  v_end_session public.reservation_inspection_sessions;
  v_settlement public.reservation_inspection_settlements;
  v_dispute public.reservation_inspection_disputes;
  v_photo_ids text[];
  v_photo_count integer;
  v_inserted_count integer;
  v_desc text := coalesce(trim(p_description), '');
BEGIN
  IF v_role = 'anon' OR v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentification requise';
  END IF;

  SELECT r.id, r.owner_id, r.renter_id
  INTO v_reservation
  FROM public.reservations r
  WHERE r.id = p_reservation_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Reservation introuvable';
  END IF;

  IF v_user_id = v_reservation.owner_id THEN
    v_participant_role := 'owner';
  ELSIF v_user_id = v_reservation.renter_id THEN
    v_participant_role := 'renter';
  ELSE
    RAISE EXCEPTION 'Utilisateur non autorise pour cette reservation';
  END IF;

  SELECT s.*
  INTO v_end_session
  FROM public.reservation_inspection_sessions s
  WHERE s.reservation_id = p_reservation_id
    AND lower(coalesce(s.phase, '')) = 'end'
  ORDER BY s.id DESC
  LIMIT 1;

  IF NOT FOUND OR v_end_session.closed_at IS NULL THEN
    RAISE EXCEPTION 'La phase de fin de location n?est pas cloturee';
  END IF;

  IF v_end_session.contest_window_ends_at IS NULL OR now() > v_end_session.contest_window_ends_at THEN
    RAISE EXCEPTION 'Le delai de contestation de 24h est expire';
  END IF;

  IF char_length(v_desc) < 30 THEN
    RAISE EXCEPTION 'Une explication detaillee (minimum 30 caracteres) est obligatoire';
  END IF;

  SELECT coalesce(array_agg(DISTINCT trim(x)), '{}'::text[])
  INTO v_photo_ids
  FROM unnest(coalesce(p_selected_photo_ids, '{}'::text[])) AS x
  WHERE nullif(trim(x), '') IS NOT NULL;

  v_photo_count := coalesce(cardinality(v_photo_ids), 0);
  IF v_photo_count = 0 THEN
    RAISE EXCEPTION 'Vous devez selectionner au moins une photo precise';
  END IF;

  INSERT INTO public.reservation_inspection_settlements (
    reservation_id,
    end_session_id,
    status,
    payment_hold_status,
    hold_started_at,
    contest_window_ends_at,
    auto_release_eligible_at,
    created_at,
    updated_at
  )
  VALUES (
    p_reservation_id,
    v_end_session.id,
    'hold_24h',
    'hold_24h',
    v_end_session.closed_at,
    v_end_session.contest_window_ends_at,
    v_end_session.contest_window_ends_at,
    now(),
    now()
  )
  ON CONFLICT (reservation_id) DO NOTHING;

  SELECT st.*
  INTO v_settlement
  FROM public.reservation_inspection_settlements st
  WHERE st.reservation_id = p_reservation_id;

  INSERT INTO public.reservation_inspection_disputes (
    reservation_id,
    settlement_id,
    opened_by_user_id,
    opened_by_role,
    status,
    title,
    description,
    opened_at,
    window_ends_at,
    submitted_within_window,
    created_at,
    updated_at
  )
  VALUES (
    p_reservation_id,
    v_settlement.id,
    v_user_id,
    v_participant_role,
    'opened',
    nullif(trim(coalesce(p_title, '')), ''),
    v_desc,
    now(),
    v_end_session.contest_window_ends_at,
    true,
    now(),
    now()
  )
  RETURNING * INTO v_dispute;

  INSERT INTO public.reservation_inspection_dispute_photos (
    dispute_id,
    reservation_id,
    photo_id_text,
    photo_phase,
    photo_url_snapshot,
    selected_at,
    metadata
  )
  SELECT
    v_dispute.id,
    p_reservation_id,
    p.id::text,
    lower(coalesce(p.phase, '')),
    p.photo_url,
    now(),
    jsonb_build_object(
      'captured_at_server', p.captured_at_server,
      'frozen_at', p.frozen_at,
      'is_frozen', p.is_frozen
    )
  FROM public.reservation_photos p
  WHERE p.reservation_id = p_reservation_id
    AND p.id::text = ANY(v_photo_ids);

  GET DIAGNOSTICS v_inserted_count = ROW_COUNT;
  IF coalesce(v_inserted_count, 0) <> v_photo_count THEN
    RAISE EXCEPTION 'Au moins une photo selectionnee est invalide pour cette reservation';
  END IF;

  UPDATE public.reservation_inspection_settlements
  SET
    status = 'disputed_pending_moderation',
    payment_hold_status = 'frozen_for_moderation',
    dispute_opened_at = coalesce(dispute_opened_at, now()),
    payment_frozen_at = coalesce(payment_frozen_at, now()),
    dispute_count = coalesce(dispute_count, 0) + 1,
    latest_dispute_id = v_dispute.id,
    updated_at = now()
  WHERE id = v_settlement.id;

  UPDATE public.reservations
  SET
    deposit_status = 'held',
    updated_at = now()
  WHERE id = p_reservation_id;

  RETURN v_dispute;
END;
$$;

CREATE OR REPLACE FUNCTION public.process_due_reservation_inspection_settlements(
  p_limit integer DEFAULT 100
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  v_limit integer := greatest(coalesce(p_limit, 100), 1);
  v_item record;
  v_has_open_dispute boolean;
  v_processed integer := 0;
  v_released_ids uuid[] := '{}'::uuid[];
  v_frozen_ids uuid[] := '{}'::uuid[];
BEGIN
  FOR v_item IN
    SELECT st.*
    FROM public.reservation_inspection_settlements st
    WHERE st.status = 'hold_24h'
      AND st.auto_release_eligible_at IS NOT NULL
      AND st.auto_release_eligible_at <= now()
    ORDER BY st.auto_release_eligible_at ASC
    LIMIT v_limit
  LOOP
    SELECT EXISTS (
      SELECT 1
      FROM public.reservation_inspection_disputes d
      WHERE d.reservation_id = v_item.reservation_id
        AND d.status IN ('opened', 'under_review', 'pending_information')
    )
    INTO v_has_open_dispute;

    IF v_has_open_dispute THEN
      UPDATE public.reservation_inspection_settlements
      SET
        status = 'disputed_pending_moderation',
        payment_hold_status = 'frozen_for_moderation',
        payment_frozen_at = coalesce(payment_frozen_at, now()),
        updated_at = now()
      WHERE id = v_item.id;

      UPDATE public.reservations
      SET
        deposit_status = 'held',
        updated_at = now()
      WHERE id = v_item.reservation_id;

      v_frozen_ids := array_append(v_frozen_ids, v_item.reservation_id);
    ELSE
      UPDATE public.reservation_inspection_settlements
      SET
        status = 'released_no_dispute',
        payment_hold_status = 'released',
        payment_released_at = coalesce(payment_released_at, now()),
        final_decision_at = coalesce(final_decision_at, now()),
        updated_at = now()
      WHERE id = v_item.id;

      UPDATE public.reservations
      SET
        deposit_status = 'released',
        deposit_released_at = coalesce(deposit_released_at, now()),
        updated_at = now()
      WHERE id = v_item.reservation_id;

      v_released_ids := array_append(v_released_ids, v_item.reservation_id);
    END IF;

    v_processed := v_processed + 1;
  END LOOP;

  RETURN jsonb_build_object(
    'processed', v_processed,
    'released_count', coalesce(cardinality(v_released_ids), 0),
    'frozen_count', coalesce(cardinality(v_frozen_ids), 0),
    'released_reservation_ids', to_jsonb(v_released_ids),
    'frozen_reservation_ids', to_jsonb(v_frozen_ids)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.moderate_reservation_inspection_dispute(
  p_dispute_id bigint,
  p_decision text,
  p_moderator_note text DEFAULT NULL
)
RETURNS public.reservation_inspection_disputes
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_role text := coalesce(auth.role(), '');
  v_is_admin boolean := false;
  v_dispute public.reservation_inspection_disputes;
  v_settlement public.reservation_inspection_settlements;
  v_decision text := lower(coalesce(trim(p_decision), ''));
BEGIN
  IF v_role <> 'service_role' THEN
    SELECT coalesce(p.is_admin, false)
    INTO v_is_admin
    FROM public.profiles p
    WHERE p.id = v_user_id;

    IF v_user_id IS NULL OR v_is_admin IS DISTINCT FROM true THEN
      RAISE EXCEPTION 'Acces reserve ? la moderation';
    END IF;
  END IF;

  IF v_decision NOT IN ('release', 'capture', 'reject') THEN
    RAISE EXCEPTION 'Decision de moderation invalide';
  END IF;

  SELECT d.*
  INTO v_dispute
  FROM public.reservation_inspection_disputes d
  WHERE d.id = p_dispute_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Litige introuvable';
  END IF;

  UPDATE public.reservation_inspection_disputes
  SET
    status = CASE
      WHEN v_decision = 'release' THEN 'resolved_release'
      WHEN v_decision = 'capture' THEN 'resolved_capture'
      ELSE 'rejected'
    END,
    moderator_user_id = coalesce(v_user_id, moderator_user_id),
    moderator_decision = v_decision,
    moderator_note = nullif(trim(coalesce(p_moderator_note, '')), ''),
    resolved_at = now(),
    updated_at = now()
  WHERE id = p_dispute_id
  RETURNING * INTO v_dispute;

  SELECT st.*
  INTO v_settlement
  FROM public.reservation_inspection_settlements st
  WHERE st.id = v_dispute.settlement_id
     OR (v_dispute.settlement_id IS NULL AND st.reservation_id = v_dispute.reservation_id)
  ORDER BY st.id DESC
  LIMIT 1;

  IF FOUND THEN
    UPDATE public.reservation_inspection_settlements
    SET
      status = CASE
        WHEN v_decision = 'release' THEN 'released_after_moderation'
        WHEN v_decision = 'capture' THEN 'captured_after_moderation'
        ELSE status
      END,
      payment_hold_status = CASE
        WHEN v_decision = 'release' THEN 'released'
        WHEN v_decision = 'capture' THEN 'captured'
        ELSE payment_hold_status
      END,
      payment_released_at = CASE WHEN v_decision = 'release' THEN coalesce(payment_released_at, now()) ELSE payment_released_at END,
      final_decision_at = now(),
      updated_at = now()
    WHERE id = v_settlement.id;
  END IF;

  IF v_decision = 'release' THEN
    UPDATE public.reservations
    SET
      deposit_status = 'released',
      deposit_released_at = coalesce(deposit_released_at, now()),
      updated_at = now()
    WHERE id = v_dispute.reservation_id;
  ELSIF v_decision = 'capture' THEN
    UPDATE public.reservations
    SET
      deposit_status = 'captured',
      updated_at = now()
    WHERE id = v_dispute.reservation_id;
  END IF;

  RETURN v_dispute;
END;
$$;

GRANT EXECUTE ON FUNCTION public.open_reservation_inspection_dispute(uuid, text[], text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.process_due_reservation_inspection_settlements(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.moderate_reservation_inspection_dispute(bigint, text, text) TO authenticated;

-- Allow cleanup deletion of frozen inspection photos only after final settlement.
CREATE OR REPLACE FUNCTION public.enforce_reservation_photo_phase_freeze()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  v_reservation_id uuid;
  v_phase text;
  v_closed_at timestamptz;
  v_settlement_status text;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_reservation_id := OLD.reservation_id;
    v_phase := lower(coalesce(OLD.phase, ''));
  ELSE
    v_reservation_id := NEW.reservation_id;
    v_phase := lower(coalesce(NEW.phase, ''));
  END IF;

  SELECT s.closed_at
  INTO v_closed_at
  FROM public.reservation_inspection_sessions s
  WHERE s.reservation_id = v_reservation_id
    AND s.phase = v_phase
    AND s.closed_at IS NOT NULL
  ORDER BY s.closed_at DESC
  LIMIT 1;

  IF v_closed_at IS NOT NULL THEN
    IF TG_OP = 'DELETE' THEN
      SELECT lower(coalesce(st.status, ''))
      INTO v_settlement_status
      FROM public.reservation_inspection_settlements st
      WHERE st.reservation_id = v_reservation_id
      ORDER BY st.id DESC
      LIMIT 1;

      IF v_settlement_status IN ('released_no_dispute', 'released_after_moderation', 'captured_after_moderation') THEN
        RETURN OLD;
      END IF;
    END IF;

    RAISE EXCEPTION 'Les photos de cette phase d?etat des lieux sont fig?es apr?s cl?ture';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;
