-- First-party platform analytics (consent-gated in frontend).
-- Stores page views and product funnel events for admin reporting.

CREATE TABLE IF NOT EXISTS public.platform_analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name text NOT NULL,
  event_category text,
  event_source text NOT NULL DEFAULT 'web_client',
  page_path text,
  page_type text,
  page_title text,
  page_location text,
  referrer text,
  referrer_host text,
  session_id text,
  visitor_id text,
  auth_user_id uuid DEFAULT auth.uid(),
  is_authenticated boolean,
  device_type text,
  viewport_width integer,
  viewport_height integer,
  screen_width integer,
  screen_height integer,
  language text,
  timezone text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_platform_analytics_events_created_at
  ON public.platform_analytics_events(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_platform_analytics_events_event_name_created
  ON public.platform_analytics_events(event_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_platform_analytics_events_page_path_created
  ON public.platform_analytics_events(page_path, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_platform_analytics_events_session_created
  ON public.platform_analytics_events(session_id, created_at DESC);

ALTER TABLE public.platform_analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "platform_analytics_events_admin_select" ON public.platform_analytics_events;
CREATE POLICY "platform_analytics_events_admin_select"
  ON public.platform_analytics_events
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND is_admin = true
    )
  );

DROP POLICY IF EXISTS "platform_analytics_events_public_insert" ON public.platform_analytics_events;
CREATE POLICY "platform_analytics_events_public_insert"
  ON public.platform_analytics_events
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);
