-- Reinforced inspection workflow (etat des lieux):
-- - mutual presence confirmation with attestation + technical trace
-- - per-phase inspection session state machine (start/end)
-- - explicit photo finalization by each party
-- - automatic phase closure + 24h contest window
-- - server-side timestamping and freezing of reservation photos after closure

CREATE TABLE IF NOT EXISTS public.reservation_inspection_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id uuid NOT NULL REFERENCES public.reservations(id) ON DELETE CASCADE,
  phase text NOT NULL,
  status text NOT NULL DEFAULT 'awaiting_presence',
  owner_presence_confirmed_at timestamptz,
  renter_presence_confirmed_at timestamptz,
  owner_photos_finalized_at timestamptz,
  renter_photos_finalized_at timestamptz,
  closed_at timestamptz,
  contest_window_ends_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reservation_inspection_sessions_phase_check CHECK (phase IN ('start', 'end')),
  CONSTRAINT reservation_inspection_sessions_status_check CHECK (status IN ('awaiting_presence', 'awaiting_finalization', 'closed')),
  CONSTRAINT reservation_inspection_sessions_unique_reservation_phase UNIQUE (reservation_id, phase)
);

CREATE INDEX IF NOT EXISTS idx_reservation_inspection_sessions_reservation_phase
  ON public.reservation_inspection_sessions(reservation_id, phase);

CREATE INDEX IF NOT EXISTS idx_reservation_inspection_sessions_closed_at
  ON public.reservation_inspection_sessions(closed_at DESC NULLS LAST);

CREATE TABLE IF NOT EXISTS public.reservation_inspection_presence_confirmations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id uuid NOT NULL REFERENCES public.reservations(id) ON DELETE CASCADE,
  phase text NOT NULL,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  participant_role text NOT NULL,
  attestation_text text NOT NULL,
  attestation_accepted boolean NOT NULL DEFAULT true,
  confirmed_at_server timestamptz NOT NULL DEFAULT now(),
  ip_address text,
  user_agent text,
  device_fingerprint_hash text,
  device_type text,
  client_reported_coordinates text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reservation_inspection_presence_phase_check CHECK (phase IN ('start', 'end')),
  CONSTRAINT reservation_inspection_presence_role_check CHECK (participant_role IN ('owner', 'renter')),
  CONSTRAINT reservation_inspection_presence_unique_role UNIQUE (reservation_id, phase, participant_role),
  CONSTRAINT reservation_inspection_presence_unique_user UNIQUE (reservation_id, phase, user_id)
);

CREATE INDEX IF NOT EXISTS idx_reservation_inspection_presence_reservation_phase
  ON public.reservation_inspection_presence_confirmations(reservation_id, phase);

ALTER TABLE public.reservation_inspection_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservation_inspection_presence_confirmations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "inspection_sessions_participants_select" ON public.reservation_inspection_sessions;
CREATE POLICY "inspection_sessions_participants_select"
  ON public.reservation_inspection_sessions
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.reservations r
      WHERE r.id = reservation_id
        AND auth.uid() IN (r.owner_id, r.renter_id)
    )
  );

DROP POLICY IF EXISTS "inspection_presence_participants_select" ON public.reservation_inspection_presence_confirmations;
CREATE POLICY "inspection_presence_participants_select"
  ON public.reservation_inspection_presence_confirmations
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.reservations r
      WHERE r.id = reservation_id
        AND auth.uid() IN (r.owner_id, r.renter_id)
    )
  );

CREATE OR REPLACE FUNCTION public.apply_reservation_inspection_session_state()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  v_now timestamptz := now();
BEGIN
  NEW.updated_at := v_now;

  IF NEW.closed_at IS NULL
     AND NEW.owner_presence_confirmed_at IS NOT NULL
     AND NEW.renter_presence_confirmed_at IS NOT NULL
     AND NEW.owner_photos_finalized_at IS NOT NULL
     AND NEW.renter_photos_finalized_at IS NOT NULL THEN
    NEW.closed_at := v_now;
    NEW.contest_window_ends_at := coalesce(NEW.contest_window_ends_at, v_now + interval '24 hours');
  END IF;

  IF NEW.closed_at IS NOT NULL THEN
    NEW.status := 'closed';
    NEW.contest_window_ends_at := coalesce(NEW.contest_window_ends_at, NEW.closed_at + interval '24 hours');
  ELSIF NEW.owner_presence_confirmed_at IS NOT NULL
     AND NEW.renter_presence_confirmed_at IS NOT NULL THEN
    NEW.status := 'awaiting_finalization';
  ELSE
    NEW.status := 'awaiting_presence';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_apply_reservation_inspection_session_state ON public.reservation_inspection_sessions;
CREATE TRIGGER trg_apply_reservation_inspection_session_state
BEFORE INSERT OR UPDATE ON public.reservation_inspection_sessions
FOR EACH ROW
EXECUTE FUNCTION public.apply_reservation_inspection_session_state();

ALTER TABLE public.reservation_photos
  ADD COLUMN IF NOT EXISTS captured_at_server timestamptz,
  ADD COLUMN IF NOT EXISTS capture_method text,
  ADD COLUMN IF NOT EXISTS capture_source text,
  ADD COLUMN IF NOT EXISTS immutable_after_close boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_frozen boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS frozen_at timestamptz,
  ADD COLUMN IF NOT EXISTS integrity_sha256 text;

CREATE OR REPLACE FUNCTION public.set_reservation_photo_server_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
BEGIN
  NEW.captured_at_server := coalesce(NEW.captured_at_server, now());
  NEW.taken_at := NEW.captured_at_server;
  NEW.capture_source := coalesce(nullif(NEW.capture_source, ''), 'inspection_module');
  NEW.capture_method := coalesce(nullif(NEW.capture_method, ''), 'browser_camera_live');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_reservation_photo_server_fields ON public.reservation_photos;
CREATE TRIGGER trg_set_reservation_photo_server_fields
BEFORE INSERT ON public.reservation_photos
FOR EACH ROW
EXECUTE FUNCTION public.set_reservation_photo_server_fields();

CREATE OR REPLACE FUNCTION public.enforce_reservation_photo_phase_freeze()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  v_reservation_id uuid;
  v_phase text;
  v_closed_at timestamptz;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_reservation_id := OLD.reservation_id;
    v_phase := lower(coalesce(OLD.phase, ''));
  ELSE
    v_reservation_id := NEW.reservation_id;
    v_phase := lower(coalesce(NEW.phase, ''));
  END IF;

  SELECT s.closed_at
  INTO v_closed_at
  FROM public.reservation_inspection_sessions s
  WHERE s.reservation_id = v_reservation_id
    AND s.phase = v_phase
    AND s.closed_at IS NOT NULL
  ORDER BY s.closed_at DESC
  LIMIT 1;

  IF v_closed_at IS NOT NULL THEN
    RAISE EXCEPTION 'Les photos de cette phase d?etat des lieux sont fig?es apr?s cl?ture';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_reservation_photo_phase_freeze_insert ON public.reservation_photos;
CREATE TRIGGER trg_enforce_reservation_photo_phase_freeze_insert
BEFORE INSERT ON public.reservation_photos
FOR EACH ROW
EXECUTE FUNCTION public.enforce_reservation_photo_phase_freeze();

DROP TRIGGER IF EXISTS trg_enforce_reservation_photo_phase_freeze_update ON public.reservation_photos;
CREATE TRIGGER trg_enforce_reservation_photo_phase_freeze_update
BEFORE UPDATE ON public.reservation_photos
FOR EACH ROW
EXECUTE FUNCTION public.enforce_reservation_photo_phase_freeze();

DROP TRIGGER IF EXISTS trg_enforce_reservation_photo_phase_freeze_delete ON public.reservation_photos;
CREATE TRIGGER trg_enforce_reservation_photo_phase_freeze_delete
BEFORE DELETE ON public.reservation_photos
FOR EACH ROW
EXECUTE FUNCTION public.enforce_reservation_photo_phase_freeze();

CREATE OR REPLACE FUNCTION public.freeze_phase_reservation_photos_on_session_close()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
BEGIN
  IF NEW.closed_at IS NOT NULL AND (
    TG_OP = 'INSERT'
    OR OLD.closed_at IS NULL
    OR OLD.closed_at IS DISTINCT FROM NEW.closed_at
  ) THEN
    UPDATE public.reservation_photos p
    SET
      is_frozen = true,
      frozen_at = coalesce(NEW.closed_at, now())
    WHERE p.reservation_id = NEW.reservation_id
      AND lower(coalesce(p.phase, '')) = lower(coalesce(NEW.phase, ''))
      AND (p.is_frozen IS DISTINCT FROM true OR p.frozen_at IS NULL);
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_freeze_phase_reservation_photos_on_session_close ON public.reservation_inspection_sessions;
CREATE TRIGGER trg_freeze_phase_reservation_photos_on_session_close
AFTER INSERT OR UPDATE ON public.reservation_inspection_sessions
FOR EACH ROW
EXECUTE FUNCTION public.freeze_phase_reservation_photos_on_session_close();

CREATE OR REPLACE FUNCTION public.confirm_reservation_inspection_presence(
  p_reservation_id uuid,
  p_phase text,
  p_attestation_text text DEFAULT 'Je certifie etre physiquement present avec l?autre partie au moment de la prise des photos. Toute fausse declaration engage ma responsabilite.',
  p_ip_address text DEFAULT NULL,
  p_user_agent text DEFAULT NULL,
  p_device_fingerprint_hash text DEFAULT NULL,
  p_device_type text DEFAULT NULL,
  p_client_reported_coordinates text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS public.reservation_inspection_sessions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_role text := coalesce(auth.role(), '');
  v_reservation record;
  v_participant_role text;
  v_session public.reservation_inspection_sessions;
  v_phase text := lower(coalesce(p_phase, ''));
BEGIN
  IF v_role = 'anon' OR v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentification requise';
  END IF;

  IF v_phase NOT IN ('start', 'end') THEN
    RAISE EXCEPTION 'phase invalide';
  END IF;

  SELECT r.id, r.owner_id, r.renter_id
  INTO v_reservation
  FROM public.reservations r
  WHERE r.id = p_reservation_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Reservation introuvable';
  END IF;

  IF v_user_id = v_reservation.owner_id THEN
    v_participant_role := 'owner';
  ELSIF v_user_id = v_reservation.renter_id THEN
    v_participant_role := 'renter';
  ELSE
    RAISE EXCEPTION 'Utilisateur non autorise pour cette reservation';
  END IF;

  INSERT INTO public.reservation_inspection_presence_confirmations (
    reservation_id,
    phase,
    user_id,
    participant_role,
    attestation_text,
    attestation_accepted,
    confirmed_at_server,
    ip_address,
    user_agent,
    device_fingerprint_hash,
    device_type,
    client_reported_coordinates,
    metadata,
    created_at,
    updated_at
  )
  VALUES (
    p_reservation_id,
    v_phase,
    v_user_id,
    v_participant_role,
    coalesce(nullif(trim(p_attestation_text), ''), 'Je certifie etre physiquement present avec l?autre partie au moment de la prise des photos. Toute fausse declaration engage ma responsabilite.'),
    true,
    now(),
    nullif(trim(coalesce(p_ip_address, '')), ''),
    nullif(trim(coalesce(p_user_agent, '')), ''),
    nullif(trim(coalesce(p_device_fingerprint_hash, '')), ''),
    nullif(trim(coalesce(p_device_type, '')), ''),
    nullif(trim(coalesce(p_client_reported_coordinates, '')), ''),
    coalesce(p_metadata, '{}'::jsonb),
    now(),
    now()
  )
  ON CONFLICT (reservation_id, phase, participant_role)
  DO UPDATE SET
    user_id = excluded.user_id,
    attestation_text = excluded.attestation_text,
    attestation_accepted = true,
    confirmed_at_server = now(),
    ip_address = excluded.ip_address,
    user_agent = excluded.user_agent,
    device_fingerprint_hash = excluded.device_fingerprint_hash,
    device_type = excluded.device_type,
    client_reported_coordinates = excluded.client_reported_coordinates,
    metadata = excluded.metadata,
    updated_at = now();

  INSERT INTO public.reservation_inspection_sessions (
    reservation_id,
    phase,
    owner_presence_confirmed_at,
    renter_presence_confirmed_at
  )
  VALUES (
    p_reservation_id,
    v_phase,
    CASE WHEN v_participant_role = 'owner' THEN now() ELSE NULL END,
    CASE WHEN v_participant_role = 'renter' THEN now() ELSE NULL END
  )
  ON CONFLICT (reservation_id, phase)
  DO UPDATE SET
    owner_presence_confirmed_at = CASE
      WHEN v_participant_role = 'owner'
      THEN coalesce(public.reservation_inspection_sessions.owner_presence_confirmed_at, now())
      ELSE public.reservation_inspection_sessions.owner_presence_confirmed_at
    END,
    renter_presence_confirmed_at = CASE
      WHEN v_participant_role = 'renter'
      THEN coalesce(public.reservation_inspection_sessions.renter_presence_confirmed_at, now())
      ELSE public.reservation_inspection_sessions.renter_presence_confirmed_at
    END,
    updated_at = now()
  RETURNING * INTO v_session;

  SELECT s.*
  INTO v_session
  FROM public.reservation_inspection_sessions s
  WHERE s.reservation_id = p_reservation_id
    AND s.phase = v_phase;

  RETURN v_session;
END;
$$;

CREATE OR REPLACE FUNCTION public.finalize_reservation_inspection_photos(
  p_reservation_id uuid,
  p_phase text
)
RETURNS public.reservation_inspection_sessions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_role text := coalesce(auth.role(), '');
  v_reservation record;
  v_participant_role text;
  v_session public.reservation_inspection_sessions;
  v_phase text := lower(coalesce(p_phase, ''));
BEGIN
  IF v_role = 'anon' OR v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentification requise';
  END IF;

  IF v_phase NOT IN ('start', 'end') THEN
    RAISE EXCEPTION 'phase invalide';
  END IF;

  SELECT r.id, r.owner_id, r.renter_id
  INTO v_reservation
  FROM public.reservations r
  WHERE r.id = p_reservation_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Reservation introuvable';
  END IF;

  IF v_user_id = v_reservation.owner_id THEN
    v_participant_role := 'owner';
  ELSIF v_user_id = v_reservation.renter_id THEN
    v_participant_role := 'renter';
  ELSE
    RAISE EXCEPTION 'Utilisateur non autorise pour cette reservation';
  END IF;

  INSERT INTO public.reservation_inspection_sessions (
    reservation_id,
    phase,
    owner_photos_finalized_at,
    renter_photos_finalized_at
  )
  VALUES (
    p_reservation_id,
    v_phase,
    CASE WHEN v_participant_role = 'owner' THEN now() ELSE NULL END,
    CASE WHEN v_participant_role = 'renter' THEN now() ELSE NULL END
  )
  ON CONFLICT (reservation_id, phase)
  DO UPDATE SET
    owner_photos_finalized_at = CASE
      WHEN v_participant_role = 'owner'
      THEN coalesce(public.reservation_inspection_sessions.owner_photos_finalized_at, now())
      ELSE public.reservation_inspection_sessions.owner_photos_finalized_at
    END,
    renter_photos_finalized_at = CASE
      WHEN v_participant_role = 'renter'
      THEN coalesce(public.reservation_inspection_sessions.renter_photos_finalized_at, now())
      ELSE public.reservation_inspection_sessions.renter_photos_finalized_at
    END,
    updated_at = now()
  RETURNING * INTO v_session;

  SELECT s.*
  INTO v_session
  FROM public.reservation_inspection_sessions s
  WHERE s.reservation_id = p_reservation_id
    AND s.phase = v_phase;

  RETURN v_session;
END;
$$;

GRANT EXECUTE ON FUNCTION public.confirm_reservation_inspection_presence(uuid, text, text, text, text, text, text, text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_reservation_inspection_photos(uuid, text) TO authenticated;
